config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :articles
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-red-200 text-red-600 mb-6" role="alert">
    <div class="flex items-start justify-start">
      <div>
        <h4 class="font-bold">
          <%= I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase) %>
        </h4>
        <ul class="leading-normal">
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :body, class: "label" %>
    <%= form.text_area :body, class: "input" %>
  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button class: "btn btn-default" %>

    <% if form.object.persisted? %>
      <%= link_to 'Delete', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Are you sure?" } %>
    <% end %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Editing Article</h1>

    <%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="h2">Articles</h1>

    <% if @articles.exists? %>
      <%= link_to 'New Article', new_article_path, class: "btn btn-default" %>
    <% end %>
  </div>

  <% if @articles.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Title</th>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Body</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @articles.each do |article| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= article.title %></td>
                          <td class="p-3"><%= article.body %></td>
            
            <td>
              <%= link_to "View", article, class: "btn btn-default" %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-default" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center">
        <p class="text-xl font-semibold mb-4">Create your first Article</p>
      <%= link_to 'New Article', new_article_path, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">New Article</h1>

    <%= render 'form', article: @article %>

    <%= link_to 'Back', articles_path, class: "link" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container mx-auto my-8 px-4">
    <p class="text-lg font-semibold">Title:</p>
  <p class="leading-normal"><%= @article.title %></p>

    <p class="text-lg font-semibold">Body:</p>
  <p class="leading-normal"><%= @article.body %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-default mr-4" %>
    <%= link_to 'Back', articles_path, class: "btn btn-default" %>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="semibold text-2xl">Welcome to Kickstart!</h1>
<p class="lead">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickstart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-white">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="mb-4">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to "Kickstart", root_path, class:"link text-xl tracking-tight font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="lg:flex-grow">
            <%= link_to "Basic Link", "#", class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
          </div>
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">
            <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
          </div>
        </div>
      </nav>
    </header>

    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :body, class: "label" %>
    <%= form.text_area :body, class: "input" %>
  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button class: "btn btn-default" %>

    <% if form.object.persisted? %>
      <%= link_to 'Delete', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Are you sure?" } %>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Editing Post</h1>

    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="h2">Posts</h1>

    <% if @posts.exists? %>
      <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
    <% end %>
  </div>

  <% if @posts.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Title</th>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Body</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @posts.each do |post| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= post.title %></td>
                          <td class="p-3"><%= post.body %></td>
            
            <td>
              <%= link_to "View", post, class: "btn btn-default" %>
              <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center">
        <p class="text-xl font-semibold mb-4">Create your first Post</p>
      <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path, class: "link" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mx-auto my-8 px-4">
    <p class="text-lg font-semibold">Title:</p>
  <p class="leading-normal"><%= @post.title %></p>

    <p class="text-lg font-semibold">Body:</p>
  <p class="leading-normal"><%= @post.body %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default mr-4" %>
    <%= link_to 'Back', posts_path, class: "btn btn-default" %>
  </div>
</div>